export const DORM_LIST_REQUEST = 'DORM_LIST_REQUEST';

export const DORM_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const DORM_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const DORM_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
